apiVersion: v1
kind: Service
metadata:
  name: stratum-catalogue
  namespace: stratum-workloads
  labels:
    app: stratum-catalogue
spec:
  selector:
    app: stratum-catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP