apiVersion: v1
kind: Service
metadata:
  name: stratum-orders
  namespace: stratum-workloads
  labels:
    app: stratum-orders
spec:
  selector:
    app: stratum-orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP